#!/usr/bin/env bash
# to generate new list of extenstions: `code --list-extensions | xargs -L 1 echo code --install-extension`

code --install-extension 13xforever.language-x86-64-assembly
code --install-extension Vans.haskero
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.code-runner
code --install-extension freebroccolo.reasonml
code --install-extension humao.rest-client
code --install-extension humy2833.ftp-simple
code --install-extension jcanero.hoogle-vscode
code --install-extension JuanBlanco.solidity
code --install-extension justusadam.language-haskell
code --install-extension marcoms.oceanic-plus
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension mshr-h.veriloghdl
code --install-extension naumovs.theme-oceanicnext
code --install-extension PeterJausovec.vscode-docker
code --install-extension pnp.polacode
code --install-extension redhat.java
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wayou.vscode-todo-highlight
code --install-extension xabikos.JavaScriptSnippets